### ISSUE TITLE
No checkerboard visible in output image

### ISSUE THREAD

**Issue by lalet** [raamana/mrivis#3]
* mrivis version:  0.2.8
* Python version: 3.4
* Operating System:  CentOS7

### Description
from mrivis import checkerboard
plot = checkerboard('T2w_acpc.nii.gz','T2w_acpc_centos7.nii.gz',patch_size=10)
plot.savefig("T2w_tilt.png")

```
These two files are output from two operating systems.   
They are completely off w.r.t alignment and we tried to visualize the differences using checkerboard. 
But no checkerboard is visible in the output image.  
Thanks for fixing the other issue, but it would be greatly appreciated if you have any hint on this one. Please find attached the output image.
```
![t2w_tilt](https://user-images.githubusercontent.com/4597920/38693112-f55d5b08-3e53-11e8-9381-5fe38f58d254.png) @glatard

**Comment by raamana** [comment]
that's weird - did you try producing collages for them separately, and be sure that they are indeed off?

**Comment by raamana** [comment]
e.g.
```
from mrivis import collage
plot1 = collage('T2w_acpc.nii.gz')
plot2 = collage('T2w_acpc_centos7.nii.gz')

```

**Comment by lalet** [comment]
Let me try that

**Comment by lalet** [comment]
![t2w_acpc](https://user-images.githubusercontent.com/4597920/38694312-4d85f09e-3e57-11e8-9498-f9c546573b86.gif)

To give you and idea, this is how it looks using fsleyes !

**Comment by raamana** [comment]
I see - did you try different checker sizes, like 3 and 5 voxels etc.. 

Is it possible for you to share the files with me, so I can try it myself? Its perfectly fine if you can't.

**Comment by lalet** [comment]
Sure ! Can I have your mail id ?

**Comment by raamana** [comment]
It is praamana@research.baycrest.org

**Comment by raamana** [comment]
they might be too big for email - so upload to some google drive or dropbox and send a link

**Comment by raamana** [comment]
Hi Lalet,

I can see the differences with smaller patch sizes..

try this
```python

import os
from os.path import join as pjoin, abspath, realpath, basename, dirname, exists as pexists
from mrivis import checkerboard, color_mix, voxelwise_diff

test_dir = dirname(realpath(__file__))
base_dir = realpath(pjoin(test_dir, '..', '..', 'example_datasets'))
out_dir = realpath(pjoin(base_dir, 'centos_ver_diff'))
os.makedirs(out_dir, exist_ok=True)

c7 = pjoin(base_dir, 'T2w_acpc_centos7.nii.gz')
not_c7 = pjoin(base_dir, 'T2w_acpc.nii.gz')

im_sets = ((c7, not_c7, 'CentOS different versions'),
           )

num_rows = 1
num_cols = 3
img_lim = None 
rescaling='each'

patch_set = (1, 2, 3, 5, 8, 10, 25, 40)
for im_set in im_sets:
    for ps in patch_set:
        comb_id = 'checkerboard patch size {}'.format(ps)
        out_path = pjoin(out_dir, comb_id.replace(' ', '_'))
        checkerboard(im_set[0], im_set[1],
                     patch_size=ps,
                     rescale_method=rescaling,
                     num_rows=num_rows,
                     num_cols=num_cols,
                     annot=comb_id,
                     output_path=out_path)

```


Perhaps the rescale method is making a difference.. need to check.

**Comment by raamana** [comment]
change the base_dir to where the images are.

**Comment by raamana** [comment]
and `voxelwise_diff` or `color_mix` is probably better suited for this purpose:

```python

num_rows = 2
num_cols = 5
img_lim = None # [0, 4000]
rescaling='each'

for im_set in im_sets:
    comb_id = 'voxelwise_diff'
    out_path = pjoin(out_dir, comb_id.replace(' ', '_'))
    voxelwise_diff(im_set[0], im_set[1],
                   rescale_method=rescaling,
                   overlay_image=True,
                   overlay_alpha=0.7,
                   background_threshold=25,
                   num_rows=num_rows,
                   num_cols=num_cols,
                   annot=comb_id,
                   output_path=out_path)
```

**Comment by raamana** [comment]
color mix - you see the red along the borders?
![color_mix_alpha_1 00](https://user-images.githubusercontent.com/3196357/38701009-c991b1ba-3e6a-11e8-8900-1903e082aa80.png)

voxel wise diff
![voxelwise_diff](https://user-images.githubusercontent.com/3196357/38701013-cdf4c882-3e6a-11e8-9359-243540ca824b.png)

**Comment by lalet** [comment]
Yes yes ! This is awesome. Thank you @raamana

**Comment by raamana** [comment]
Hi @glatard, can you take a look at this thread, and let me know your comments? I just want to make sure I fix the bug in my checkerboard implementation if it exists.
